### ISSUE TITLE
谷歌72版生成图片显示异常

### ISSUE THREAD

**Issue by Mr-Pro** [joaner/namedavatar#3]
好似最新版本不能使用 `data:image/svg+xml,<svg>......</svg>`
可能需要使用base64编码后呈现
`data:image/svg+xml;base64, ${Base64.encode('<svg>......</svg>')}`

**Comment by joaner** [comment]
我测试 chrome 72/73 for mac 都是正常的，请问是SVG图片不能显示了，还是显示的不太对？

**Comment by Mr-Pro** [comment]
是不能显示了，不知道是不是计算机环境问题？这里是`win81/10`下`chrome72/73`都有这个问题`svg`标签使用`base64`编码后加入就没有显示问题
![20190414231648](https://user-images.githubusercontent.com/26507179/56095089-d091b600-5f0b-11e9-9b81-ff9857925de7.png)
![20190414231654](https://user-images.githubusercontent.com/26507179/56095091-d12a4c80-5f0b-11e9-9f1a-78e9e30ecd27.png)

**Comment by joaner** [comment]
我这边测试Windows chrome 72 和 firefox 56 不编码也可以正常显示，不过为了保险起见，我在下个版本会改成base64编码的，明天发布

**Comment by joaner** [comment]
hello, 新发布了一个版本1.0.1，会将图片data uri转base64显示了。
不过问题的原因我还是不太确定，你要是有空也可以帮忙分析下，谢谢啦

**Comment by Mr-Pro** [comment]
同样感谢你的开源，今天看了下`Base64`编码不编码与的区别，发现就是因为使用了十六进制颜色表示导致问题，我在`chrome 63`版测试发现没有问题，新版谷歌火狐测试出现问题。主要可能就是因为十六进制颜色表示其`#`被当做hash锚点处理，这浏览器就抛出了解析错误异常
![微信截图_20190416015055](https://user-images.githubusercontent.com/26507179/56154255-a662f580-5fea-11e9-9c71-8b441370f94d.png)
![微信截图_20190416014908](https://user-images.githubusercontent.com/26507179/56154256-a6fb8c00-5fea-11e9-9444-ab944e945ffd.png)
![微信截图_20190416015214](https://user-images.githubusercontent.com/26507179/56154257-a6fb8c00-5fea-11e9-8367-db28499d3f5f.png)
![微信截图_20190416015341](https://user-images.githubusercontent.com/26507179/56154260-a7942280-5fea-11e9-95f5-724f2aca69d8.png)

**Comment by joaner** [comment]
太感谢你了，我稍后会修复这个点，编码特殊字符

**Comment by Mr-Pro** [comment]
嗯嗯，因为H5和小程序都有这方面的需求，小程序方面由于不能操作`document`会出现错误，这里简单地修改了下源码，主要是去除`document`操作，采用字符串拼接方式，希望这里下一版也能支持小程序，方便更多有类似需求的人
```javascript
namedavatar.getDataURL:

const rect = `<rect fill="${this.getBackgroundColor()}" x="0" y="0" width="100%" height="100%"></rect>`
let text = ''
if (typeof this.name === 'string' && this.name.length > 0) {
  text = `<text fill="${this.getTextColor()}" x="50%" y="50%" text-anchor="middle" alignment-baseline="central" font-size="${this.getFontSize()}" font-family="${this.getFontFamily()}">${this.name}</text>`
}
const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${rect}${text}</svg>`

return `data:image;base64,${Base64.encodeToSafeURL(svg)}`

```

**Comment by joaner** [comment]
好的，谢谢你的建议，下一个版本会支持不使用DOM的方式

**Comment by joaner** [comment]
> 嗯嗯，因为H5和小程序都有这方面的需求，小程序方面由于不能操作`document`会出现错误，这里简单地修改了下源码，主要是去除`document`操作，采用字符串拼接方式，希望这里下一版也能支持小程序，方便更多有类似需求的人
> 
> ```js
> namedavatar.getDataURL:
> 
> const rect = `<rect fill="${this.getBackgroundColor()}" x="0" y="0" width="100%" height="100%"></rect>`
> let text = ''
> if (typeof this.name === 'string' && this.name.length > 0) {
>   text = `<text fill="${this.getTextColor()}" x="50%" y="50%" text-anchor="middle" alignment-baseline="central" font-size="${this.getFontSize()}" font-family="${this.getFontFamily()}">${this.name}</text>`
> }
> const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="${width}" height="${height}">${rect}${text}</svg>`
> 
> return `data:image;base64,${Base64.encodeToSafeURL(svg)}`
> ```

hello，新发布了1.1.0版本，支持小程序等不支持DOM操作的平台，使用方法：
```javascript
import namedavatar from 'namedavatar'

// 使用字符串拼接方式创建svg html文本
const svg = namedavatar.getSVGString('李连杰')

// 将html文本转为data uri资源
const uri = namedavatar.getDataURI(svg)

console.log(uri)
// data:image/svg+xml,%3Csvg%20...
```

**Comment by Mr-Pro** [comment]
谢谢你的更新
